spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

